---
functional:
  - Возможность зарегистрироваться на сайте
  - Возможность авторизоваться на сайте
  - Возможность создавать игру
  - Возможность участвовать в существующих играх
  - Возможность играть с другом
  - Возможность играть с ботом
  - Возможность решать задачи на выбранном языке программирования
  - Возможность общаться с соперниками и зрителями в чате
  - Возможность выбрать один из языков программирования (JavaScript, PHP, Python и Ruby). 
  - Возможность просмотра рейтингов игроков
  - Возможность видеть результаты запуска тестов и код соперника в реальном времени
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Открытый исходный код
  - Возможность повторно подключиться к игре при потере соединения до завершения игры
  - Возможность оставить обратную связь об ошибках
